function buildNetworkDeps() {
  return {
    HELD_ITEM_BUCKET,
    MAIN_BUCKET_ID,
    REMOTE_BUTTERFLY_CATCH_ACTION_MS,
    WORLD_ROCK_PICKUP_ACTION_MS,
    WORLD_ROCK_SIZE,
    accountDisplayNameForUi,
    addBucketTrace,
    get adminDebugPlantIndexBonus() { return adminDebugPlantIndexBonus; },
    set adminDebugPlantIndexBonus(v) { adminDebugPlantIndexBonus = v; },
    appStorageKeysSharedWorldReset,
    applyButterflySnapshot,
    applyDefaultState,
    applyLoadedPlantState,
    applyPlantWaterDecay,
    applyRemoteSharedMainBucketGround,
    applyRemoteSharedMainBucketHeldPose,
    applyWorldExtraBucketsFromSharedSnapshot,
    clearGroundExtraSeedElementsOnly,
    clearMainSeedPickedForCurrentRoom,
    clearMultiplayerReconnectTimeout,
    clearMultiplayerRoomSessionTracking,
    clearStoredKeys,
    craftFurnitureInstallingKind,
    get currentSessionId() { return currentSessionId; },
    set currentSessionId(v) { currentSessionId = v; },
    currentUserId,
    dropBucket,
    ensureWorldLooseSeedShape,
    extraSeedHasCorrespondingExtraPlant,
    getApple,
    getButterflyStateForSnapshot,
    getInventory,
    getMainBucketGroundState,
    getMainDryAfterEmptyMsForPlant,
    getMultiplayerWorldPollMinMs,
    getNpc,
    getPlant,
    getPlantSoilSrc,
    getPlantStateForStorage,
    getPlayer,
    getSeedWorld,
    getSharedPlantSimulationNow,
    getSynchronizedNow,
    getWell,
    getWorldItems,
    handleRemoteButterflyCatchBroadcast,
    handleRemoteButterflyStateBroadcast,
    handleRemoteWorldBagDropBroadcast,
    handleRemoteWorldBagDropPickupBroadcast,
    handleRemoteWorldLooseSeedPickupBroadcast,
    handleRemoteWorldRockPickupBroadcast,
    get hasHydratedSharedWorldFromServer() { return hasHydratedSharedWorldFromServer; },
    set hasHydratedSharedWorldFromServer(v) { hasHydratedSharedWorldFromServer = v; },
    hasPickedMainSeedInCurrentRoom,
    hasSpawnedCharacter,
    get ignoreSnapshotInventorySeedsUntil() { return ignoreSnapshotInventorySeedsUntil; },
    set ignoreSnapshotInventorySeedsUntil(v) { ignoreSnapshotInventorySeedsUntil = v; },
    invalidateGroundSeedElementRefsOnly,
    get isApplyingWorldState() { return isApplyingWorldState; },
    set isApplyingWorldState(v) { isApplyingWorldState = v; },
    isExtraSeedOwnedByLocalPlayer,
    isExtraSeedSessionOwnedByLocal,
    isHoldingExtraBucket,
    isHoldingMainBucket,
    get isMultiplayerSubscribed() { return isMultiplayerSubscribed; },
    set isMultiplayerSubscribed(v) { isMultiplayerSubscribed = v; },
    isPowderUpgradeInProgress,
    get isReloadingForWorldReset() { return isReloadingForWorldReset; },
    set isReloadingForWorldReset(v) { isReloadingForWorldReset = v; },
    isRemotePresenceSameLoggedInAccount,
    isSharedWorldMergeActive,
    isSharedWorldSyncPausedForTutorial,
    isTabSessionSuperseded,
    get isWorldDirty() { return isWorldDirty; },
    set isWorldDirty(v) { isWorldDirty = v; },
    isWorldDocumentEntry,
    get isWorldPolling() { return isWorldPolling; },
    set isWorldPolling(v) { isWorldPolling = v; },
    isWorldServerSyncAvailable,
    get isWorldSyncing() { return isWorldSyncing; },
    set isWorldSyncing(v) { isWorldSyncing = v; },
    get lastAppliedWorldResetToken() { return lastAppliedWorldResetToken; },
    set lastAppliedWorldResetToken(v) { lastAppliedWorldResetToken = v; },
    get lastBucketBroadcastAt() { return lastBucketBroadcastAt; },
    set lastBucketBroadcastAt(v) { lastBucketBroadcastAt = v; },
    get lastButterflyRealtimeStateAt() { return lastButterflyRealtimeStateAt; },
    set lastButterflyRealtimeStateAt(v) { lastButterflyRealtimeStateAt = v; },
    get lastButterflyStateChangeAt() { return lastButterflyStateChangeAt; },
    set lastButterflyStateChangeAt(v) { lastButterflyStateChangeAt = v; },
    lastLocalButterflyCatchActionAt,
    lastLocalWorldRockPickupAt,
    get lastPresenceSentAt() { return lastPresenceSentAt; },
    set lastPresenceSentAt(v) { lastPresenceSentAt = v; },
    get lastServerClockSyncAt() { return lastServerClockSyncAt; },
    set lastServerClockSyncAt(v) { lastServerClockSyncAt = v; },
    lastWaterSplashAt,
    lastWaterSplashX,
    lastWaterSplashY,
    get lastWorldPollAt() { return lastWorldPollAt; },
    set lastWorldPollAt(v) { lastWorldPollAt = v; },
    get lastWorldResetAt() { return lastWorldResetAt; },
    set lastWorldResetAt(v) { lastWorldResetAt = v; },
    get lastWorldSaveAt() { return lastWorldSaveAt; },
    set lastWorldSaveAt(v) { lastWorldSaveAt = v; },
    get lastWorldUpdatedAt() { return lastWorldUpdatedAt; },
    set lastWorldUpdatedAt(v) { lastWorldUpdatedAt = v; },
    get localAppleActionLockUntil() { return localAppleActionLockUntil; },
    set localAppleActionLockUntil(v) { localAppleActionLockUntil = v; },
    get localPlantActionLockUntil() { return localPlantActionLockUntil; },
    set localPlantActionLockUntil(v) { localPlantActionLockUntil = v; },
    mainDrySeedHandledKey,
    markWorldDirty,
    maxWellWater,
    mergeWorldBagDropsFromSnapshot,
    get multiplayerChannel() { return multiplayerChannel; },
    set multiplayerChannel(v) { multiplayerChannel = v; },
    get multiplayerConnectAttempt() { return multiplayerConnectAttempt; },
    set multiplayerConnectAttempt(v) { multiplayerConnectAttempt = v; },
    nameForIngameUiDisplay,
    get networkDebugDomStale() { return networkDebugDomStale; },
    set networkDebugDomStale(v) { networkDebugDomStale = v; },
    get networkDebugLines() { return networkDebugLines; },
    set networkDebugLines(v) { networkDebugLines = v; },
    networkDebugPanel,
    normalizePlantSproutFieldsWhenSoilDry,
    ovcTryDismissLoadingScreen,
    ovcWorldIndexUrl,
    parsePlacedCraftFurnitureFromSnapshot,
    parseSharedGroundSeedFromSnapshot,
    get pendingForceWorldSaveAfterPoll() { return pendingForceWorldSaveAfterPoll; },
    set pendingForceWorldSaveAfterPoll(v) { pendingForceWorldSaveAfterPoll = v; },
    get pendingWorldResetToken() { return pendingWorldResetToken; },
    set pendingWorldResetToken(v) { pendingWorldResetToken = v; },
    persistOvcLastAppliedWorldResetToken,
    get placedCraftFurniture() { return placedCraftFurniture; },
    set placedCraftFurniture(v) { placedCraftFurniture = v; },
    plantSpot,
    pruneDuplicateRemotePlayerSessions,
    pruneGroundExtraSeedsShadowedByPlants,
    rebasePlantModelTimestampsToLocalNow,
    rebuildPlacedCraftFurnitureDom,
    refillWellIfNeeded,
    refreshUiAfterSharedWorldApply,
    get remoteBucketUpdateAtById() { return remoteBucketUpdateAtById; },
    set remoteBucketUpdateAtById(v) { remoteBucketUpdateAtById = v; },
    get remotePlayerHeldBucketById() { return remotePlayerHeldBucketById; },
    set remotePlayerHeldBucketById(v) { remotePlayerHeldBucketById = v; },
    get remotePlayers() { return remotePlayers; },
    set remotePlayers(v) { remotePlayers = v; },
    removeRemotePlayer,
    restartPlayerPositionOnly,
    sanitizePrematureRemotePlantDryState,
    sanitizeSharedPlantHydrationAfterRemoteSnapshot,
    sanitizeWorldLooseModeExtraSeeds,
    savePlayerPosition,
    scheduleMultiplayerReconnect,
    seedCreatedAtKey,
    selectedPlayerColor,
    sendPendingPreviousSessionLeaveBroadcast,
    serializePlacedCraftFurnitureForSnapshot,
    serializeWorldBagDropsForSnapshot,
    serializeWorldExtraBucketsForSnapshot,
    get serverClockOffsetMs() { return serverClockOffsetMs; },
    set serverClockOffsetMs(v) { serverClockOffsetMs = v; },
    setMainSeedPickedForCurrentRoom,
    setStoredFlag,
    setStoredValue,
    setWorldPosition,
    shouldDeferRemoteAppleApply,
    shouldHideSeparateSoilUnderBigGrass,
    shouldIgnoreEmptyRemoteMainPlant,
    shouldPauseWaterDecayForPlant,
    showThrottledWorldSyncToast,
    stabilizeFirstWaterHintFlags,
    syncWorldLoosePickupLock,
    teardownExtraPlantDom,
    teardownMultiplayerForTutorial,
    updateMultiplayerStatus,
    updatePlantProgressGauge,
    updateRemotePlayerCount,
    usesWorldLooseSeedMode,
    get worldSaveConflictBackoffUntil() { return worldSaveConflictBackoffUntil; },
    set worldSaveConflictBackoffUntil(v) { worldSaveConflictBackoffUntil = v; },
  };
}
