function buildSystemsDeps() {
  return {
    PLAYER_WIDTH,
    WORLD_WIDTH,
    addPlantWorldRockAvoidZone,
    get adminDebugPlantIndexBonus() { return adminDebugPlantIndexBonus; },
    set adminDebugPlantIndexBonus(v) { adminDebugPlantIndexBonus = v; },
    appleRespawnMs,
    appleStateKey,
    applyButterflyCatchable,
    applyButterflyFacing,
    applyButterflySpriteFrame,
    applyPlantWaterDecay,
    areButterfliesUnlockedForPlantFogWorld,
    areButterfliesUnlockedForTutorialOnboarding,
    authorityFillToCapInstantly,
    authoritySpawnButterfliesIfNeeded,
    broadcastButterflyState,
    bucket,
    buildWorldBagDropElement,
    buildWorldRockSpawnContext,
    get butterflyAuthorityWaypointById() { return butterflyAuthorityWaypointById; },
    set butterflyAuthorityWaypointById(v) { butterflyAuthorityWaypointById = v; },
    butterflyBoundsBottom,
    butterflyBoundsLeft,
    butterflyBoundsRight,
    butterflyBoundsTop,
    butterflyBroadcastMs,
    butterflyCatchDistance,
    butterflyColors,
    butterflyFrameCount,
    butterflyFrameMs,
    butterflyMaxAlive,
    BUTTERFLY_SIZE,
    butterflyMotion,
    get butterflyRenderById() { return butterflyRenderById; },
    set butterflyRenderById(v) { butterflyRenderById = v; },
    butterflyRespawnMs,
    get butterflyState() { return butterflyState; },
    set butterflyState(v) { butterflyState = v; },
    cactusLevel5GrowMs,
    canDiscardBagItemKey,
    cancelTradeOnPlayerHealthDepleted,
    clampButterflyPointToActiveBounds,
    clampPlayerToTreeOutline,
    clearLiveButterfliesForPlantFogLock,
    collectWorldRockAvoidZones,
    get craftFurnitureInstallingKind() { return craftFurnitureInstallingKind; },
    set craftFurnitureInstallingKind(v) { craftFurnitureInstallingKind = v; },
    createButterfly,
    createDefaultWorldLooseSeedRecord,
    createRandomApple,
    get currentSessionId() { return currentSessionId; },
    set currentSessionId(v) { currentSessionId = v; },
    ensureButterflyRenderEntry,
    ensureWorldBagDropsArray,
    ensureWorldLooseSeedShape,
    expandWorldRockAvoidRect,
    formatWorldBagDropCountLabel,
    getActiveButterflyBounds,
    getApple,
    getAutoTier5GrowMsForPlant,
    getLocalRockMining,
    getBagDropGroundVisual,
    getBagDropStackKey,
    getBucketSize,
    getButterflyAnimationFrame,
    getButterflyCatchDistanceAtWorldCenter,
    getButterflyStateForSnapshot,
    getCenterDistance,
    getCenterDistanceUtil,
    getCraftChairById,
    getCraftChairSitPose,
    getDefaultButterflyBounds,
    getDefaultButterflyFlyBoundsWorldPx,
    getButterflyFlyBoundsWorldPx,
    getGrassAutoTier5GrowthRatio,
    getLocalPlayerBodyHeight,
    getLocalPlayerBodyWidth,
    getMaxGroundedPlayerDepth,
    getMaxTreePlayerDepth,
    getMinGroundedPlayerDepth,
    getMinPlantCenterClearanceWorld,
    getMinTreePlayerDepth,
    getNpc,
    getNumericButterflyValue,
    getNumericButterflyValueCore,
    getOnboarding,
    getPlant,
    getPlantFirstGrowthDurationMs,
    getPlantFogClearRectForCurrentScore,
    getPlantFogClearRectForMovementClamp,
    getPlantFogClearRectWorldPx,
    getPlantFogWorldStageFromScore,
    getPlantGrowthRatio,
    getPlantIndexScoringOptions,
    getPlantMaturityLevelForPlantingSpacing,
    getPlantSecondGrowthRatio,
    getPlantStateForStorage,
    getPlantWaterCapacity,
    getPlantWaterLevelTickMsForPlant,
    getPlayer,
    getPlayerBox,
    getPlayerCenterX,
    getPlayerFootY,
    getPlayerHeadFogProbeBoxForPose,
    getPlayerHealthTickContext,
    getPlayerWorldRockCollisionBoxForPose,
    getPlayerWorldY,
    getPowderUpgradeRatio,
    getSeedWorld,
    getSharedPlantSimulationNow,
    getSproutStageFromPlant,
    getStoredFlag,
    getSynchronizedNow,
    getTotalPlantIndexScore,
    getUnpickedWorldRockCount,
    getVisibleWorldRockCollisionRect,
    getVisibleWorldRockCollisionRectFromBox,
    getWell,
    getWellSize,
    getWorldBagDropZIndex,
    getWorldItems,
    gravity,
    ground,
    groundFootInset,
    hasActiveGreenGrowthProgress,
    hasFreshButterflyAuthorityBroadcast,
    get hasHydratedSharedWorldFromServer() { return hasHydratedSharedWorldFromServer; },
    set hasHydratedSharedWorldFromServer(v) { hasHydratedSharedWorldFromServer = v; },
    get hasSeededInitialButterflies() { return hasSeededInitialButterflies; },
    set hasSeededInitialButterflies(v) { hasSeededInitialButterflies = v; },
    get hasSpawnedCharacter() { return hasSpawnedCharacter; },
    set hasSpawnedCharacter(v) { hasSpawnedCharacter = v; },
    isAlchemyCraftOpen,
    isAlchemyMasterDialogueRunning,
    isAppleInTrunkArea,
    isApplyingWorldState,
    isButterflyAuthority,
    isCactusMaturePlant,
    get isCharacterSelecting() { return isCharacterSelecting; },
    set isCharacterSelecting(v) { isCharacterSelecting = v; },
    isCraftFurnitureInstalling,
    isLocalRockMining,
    isMainGameTutorialInProgress,
    isNearWellForCard,
    isOverlappingRect,
    isPlantFogMovementClampActive,
    isPlayerBoxFullyInsidePlantFogClearRect,
    isPlayerCollidingVisibleWorldRockForPose,
    isPlayerGameplayBlockedByNpcDialogue,
    isPlayerHeadFogClearForPose,
    isPlayerInTreeCanopy,
    isPlayerInWellWaterArea,
    isPlayerInsideEnteredCraftHouse,
    isPlayerMovementKeyActive,
    isPlayerNearTreeTrunk,
    isPlayerPoseUnchanged,
    isPlayerSupportedByTree,
    isPlayerTimedActionBusy,
    isPowderUpgradeInProgress,
    isSharedWorldMergeActive,
    isSproutStage3Or5IdleNoGrowth,
    get isTabSessionSuperseded() { return isTabSessionSuperseded; },
    set isTabSessionSuperseded(v) { isTabSessionSuperseded = v; },
    isTradeExchangeOpen,
    isTradeMasterDialogueRunning,
    isWorldBagDropExpired,
    isWorldChatBlockingGameInput,
    get isWorldDirty() { return isWorldDirty; },
    set isWorldDirty(v) { isWorldDirty = v; },
    isWorldDocumentEntry,
    isWorldRockPickupUnlocked,
    isWorldServerSyncAvailable,
    keepButterfliesInsideActiveBounds,
    lastButterflyBroadcastAt,
    get lastButterflyStateChangeAt() { return lastButterflyStateChangeAt; },
    set lastButterflyStateChangeAt(v) { lastButterflyStateChangeAt = v; },
    get lastButterflyWallClockMs() { return lastButterflyWallClockMs; },
    set lastButterflyWallClockMs(v) { lastButterflyWallClockMs = v; },
    lastRemoteWaterSplashAppliedAtBySession,
    lastWellRefillKey,
    lastWorldBagDropChangeAt,
    lastWorldBagDropDespawnAt,
    level5GrowMs,
    get localApplePickedAtById() { return localApplePickedAtById; },
    set localApplePickedAtById(v) { localApplePickedAtById = v; },
    localPlayerRoot,
    markWorldDirty,
    maxWellWater,
    getWellMaxWater,
    getWellRefillMs,
    pickSharedWorldRockRespawnPosition,
    refreshWellUpgradeCardUi,
    movePlayerVerticallyInTree,
    multiplayerChannel,
    multiplayerRoomSessionButterflyStateLastSeen,
    normalizeWorldLooseSeedRecord,
    onboardingFlowDoneKey,
    pickRandomWorldRockSpawnPosition,
    get placedCraftFurniture() { return placedCraftFurniture; },
    set placedCraftFurniture(v) { placedCraftFurniture = v; },
    plantSpot,
    player,
    playerHealthKey,
    get playerPositionChangedThisTick() { return playerPositionChangedThisTick; },
    set playerPositionChangedThisTick(v) { playerPositionChangedThisTick = v; },
    pruneButterflyAuthorityWaypointsToList,
    pruneStaleMultiplayerRoomSessions,
    remotePlayerStateStore,
    get remotePlayers() { return remotePlayers; },
    removeButterflyRenderEntry,
    removeExpiredWorldBagDrops,
    resetInputKeys,
    resetPlayerChairSitState,
    saveAppleState,
    saveAppleStateToStorage,
    savePlayerHealthState,
    saveSeedState,
    saveSeedStateToStorage,
    saveWellStateToStorage,
    seedCreatedAtKey,
    seedPlantedStateKey,
    sendMultiplayerPresence,
    serializePlacedCraftFurnitureForSnapshot,
    serverClockOffsetMs,
    setInstantHoverTip,
    setStoredValue,
    setWorldPosition,
    setWorldPositionUtil,
    setWorldSize,
    setWorldSizeUtil,
    shouldPauseWaterDecayForPlant,
    shouldRunButterflyMotionSimulation,
    shouldSkipPlantWaterDecayNow,
    simulateButterflyAuthorityStep,
    snapPlayerToCraftChair,
    sortWorldBagDropsForRender,
    spawnPortalHeight,
    spawnPortalWidth,
    spawnPortalX,
    spawnPortalY,
    speed,
    sproutStage1Ms,
    sproutStage2GrowMs,
    standUpFromChair,
    sumPlantIndexScoreForPlants,
    suppressPlantWaterDecayUntilSim,
    syncWorldState,
    teardownWorldBagDropDom,
    treeClimbSpeed,
    treeFallSpeed,
    treeMoveSpeed,
    tryRespawnOneWorldRockIfBelowCap,
    updatePlayerColorBodyPosition,
    updateWellCard,
    updateWellImage,
    updateWorldBagDropDom,
    updateWorldRockMineGauges,
    updateWorldRocks,
    WORLD_ROCK_MINE_MS,
    well,
    wellCard,
    wellCardDistance,
    wellCardImage,
    wellRefillMs,
    wellUpgradeLevelKey,
    wellDonationKrwKey,
    wellWaterFill,
    wellWaterKey,
    wellWaterText,
    world,
    worldChatInputEl,
    worldChatPanelOpen,
    worldRockOverlapsAnyAvoidRect,
    worldRockRect,
    worldSocialUiReady,
  };
}
